version: '3.9'

services:
  redis:
    image: redis:7-alpine
    container_name: Droid-api-usage-redis
    restart: unless-stopped
    volumes:
      - redis-data:/data
      - ./docker/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        - GOPROXY=${GOPROXY:-https://proxy.golang.org,direct}
    container_name: Droid-api-usage
    restart: unless-stopped
    ports:
      - "6413:8080"
    environment:
      - REDIS_URL=redis://redis:6379/0
      - ADMIN_PASSWORD=
      - LOG_LEVEL=info
      - MAX_WORKERS=500
      - QUEUE_SIZE=50000
      - HTTP_TIMEOUT=30s
      - CACHE_TTL=300s
      - SESSION_TTL=168h
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 128M

volumes:
  redis-data:
    driver: local
